// Reveal.js configuration
Reveal.initialize({
    hash: true,
    controls: true,
    progress: true,
    center: true,
    touch: true,
    loop: false,
    rtl: false,
    navigationMode: 'default',
    shuffle: false,
    fragments: true,
    fragmentInURL: false,
    embedded: false,
    help: true,
    pause: true,
    showNotes: false,
    autoPlayMedia: null,
    preloadIframes: null,
    autoAnimate: true,
    autoAnimateMatcher: null,
    autoAnimateEasing: 'ease',
    autoAnimateDuration: 1.0,
    autoAnimateUnmatched: true,
    autoSlide: 0,
    autoSlideStoppable: true,
    defaultTiming: null,
    mouseWheel: false,
    previewLinks: false,
    postMessage: true,
    postMessageEvents: false,
    focusBodyOnPageVisibilityChange: true,
    transition: 'slide',
    transitionSpeed: 'default',
    backgroundTransition: 'fade',
    parallaxBackgroundImage: '',
    parallaxBackgroundSize: '',
    parallaxBackgroundRepeat: '',
    parallaxBackgroundPosition: '',
    parallaxBackgroundOpacity: null,
    viewDistance: 3,
    mobileViewDistance: 2,
    display: 'block',
    hideInactiveCursor: true,
    hideCursorTime: 5000,
    plugins: [ RevealHighlight, RevealMarkdown, RevealNotes, RevealSearch, RevealZoom ]
});

